[project]
name = "phd-rag"
version = "0.1.0"
description = ""
authors = [
    {name = "Andrew Chung",email = "achun46@emory.edu"}
]
readme = "README.md"
requires-python = ">=3.10,<4.0"
dependencies = [
    "langchain (>=0.3.14,<0.4.0)",
    "fastapi (>=0.115.6,<0.116.0)",
    "uvicorn[standard] (>=0.34.0,<0.35.0)",
    "pymilvus[model] (>=2.5.3,<3.0.0)",
    "huggingface (>=0.0.1,<0.0.2)",
    "langchain-milvus (>=0.1.8,<0.2.0)",
    "scipy (>=1.15.1,<2.0.0)",
    "anthropic (>=0.43.1,<0.44.0)",
    "pydantic-settings (>=2.7.1,<3.0.0)",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"